### ISSUE TITLE
cannot install view ember install:addon

### ISSUE THREAD

**Issue by oriSomething** [ebryn/ember-ionic#1]
ember-cli: v0.2.2
os: osx 10.10.2

i succeed to install other addons

error:

```
.../node_modules/ember-ionic/blueprints/ember-ionic/index.js:11
  normalizeEntityName: function() {}, // no-op since we're just adding depende
  ^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Blueprint.load (.../node_modules/ember-cli/lib/models/blueprint.js:1120:23)
    at Function.Blueprint.lookup (.../node_modules/ember-cli/lib/models/blueprint.js:1097:24)
    at Class.module.exports.Task.extend.lookupBlueprint (.../node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:75:22)
```

**Comment by ebryn** [comment]
Fixed by #2
